### ISSUE TITLE
Jekyll site

### ISSUE THREAD

**Issue by israelperezglez** [arrow-kt/ank#28]
I will create a Jekyll site

**Comment by israelperezglez** [comment]
@Guardiola31337 You can assign to me this issue please? I don't have permission ;) Thanks

**Comment by Guardiola31337** [comment]
@israelperezglez weren't you an ΛRROW maintainer yet?

I've just added you! 

Now, you should be able to assign tickets across the different repositories of the [ΛRROW org](https://github.com/arrow-kt).

**Comment by israelperezglez** [comment]
@Guardiola31337 perfect, thanks ;)
